// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Type *string `json:"@type,omitempty"`

	// Password Informatica Intelligent Cloud Services password.
	Password string `json:"password"`

	// Username Informatica Intelligent Cloud Services user name for the organization that you want to log in to.
	Username string `json:"username"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAgentInstallerInfo request
	GetAgentInstallerInfo(ctx context.Context, platform string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LoginWithBody request with any body
	LoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Login(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAgentInstallerInfo(ctx context.Context, platform string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAgentInstallerInfoRequest(c.Server, platform)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Login(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAgentInstallerInfoRequest generates requests for GetAgentInstallerInfo
func NewGetAgentInstallerInfoRequest(server string, platform string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "platform", runtime.ParamLocationPath, platform)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/agent/installerInfo/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLoginRequest calls the generic Login builder with application/json body
func NewLoginRequest(server string, body LoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewLoginRequestWithBody generates requests for Login with any type of body
func NewLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ma/api/v2/user/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAgentInstallerInfoWithResponse request
	GetAgentInstallerInfoWithResponse(ctx context.Context, platform string, reqEditors ...RequestEditorFn) (*GetAgentInstallerInfoResponse, error)

	// LoginWithBodyWithResponse request with any body
	LoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginResponse, error)

	LoginWithResponse(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginResponse, error)
}

type GetAgentInstallerInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Type                *string `json:"@type,omitempty"`
		ChecksumDownloadUrl *string `json:"checksumDownloadUrl,omitempty"`
		DownloadUrl         *string `json:"downloadUrl,omitempty"`
		InstallToken        *string `json:"installToken,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetAgentInstallerInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAgentInstallerInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// CreateTime When the user account was created.
		CreateTime *string `json:"createTime,omitempty"`

		// CreatedBy Informatica Intelligent Cloud Services user who created the user account.
		CreatedBy *string `json:"createdBy,omitempty"`

		// Description Description of the user.
		Description *string `json:"description,omitempty"`

		// Emails Email address to be notified when the user changes the account password.
		Emails *string `json:"emails,omitempty"`

		// FirstName First name for the user account.
		FirstName *string `json:"firstName,omitempty"`

		// ForceChangePassword Determines if the user must reset the password after the user logs in for the first time. Includes the following values:
		// True. The user must reset the password.
		// False. The user is not forced to reset the password.
		ForceChangePassword *bool `json:"forceChangePassword,omitempty"`

		// IcSessionId Informatica Intelligent Cloud Services session ID for version 2 REST API session.
		// Use in most version 2 REST API request headers.
		IcSessionId *string `json:"icSessionId,omitempty"`

		// Id User ID.
		Id *string `json:"id,omitempty"`

		// LastName Last name for the user account.
		LastName *string `json:"lastName,omitempty"`

		// Name Informatica Intelligent Cloud Services user name.
		Name *string `json:"name,omitempty"`

		// OrgId ID of the organization the user belongs to. 22 characters.
		// NOTE: Organizations that were created in legacy Informatica Cloud might have an
		// organization ID of 6 characters.
		OrgId *string `json:"orgId,omitempty"`

		// OrgUuid Unique identifier for the organization.
		OrgUuid *string `json:"orgUuid,omitempty"`

		// Password Salesforce user password. Included when user is configured to authenticate through Salesforce.
		Password *string `json:"password,omitempty"`

		// Phone Phone number for the user.
		Phone *string `json:"phone,omitempty"`

		// Roles Object that includes a role object for each role assigned to the user.
		Roles *struct {
			// Description Role description.
			Description *string `json:"description,omitempty"`

			// Name Role name. Returns one of the following codes:
			// Service Consumer
			// Designer
			// Admin
			Name *string `json:"name,omitempty"`
		} `json:"roles,omitempty"`

		// SecurityAnswer Answer to the security question.
		SecurityAnswer *string `json:"securityAnswer,omitempty"`

		// SecurityQuestion Security question. Returns one of the following codes:
		// SPOUSE_MEETING_CITY
		// FIRST_JOB_CITY
		// CHILDHOOD_FRIEND
		// MOTHER_MAIDEN_NAME
		// PET_NAME
		// CHILDHOOD_NICKNAME
		// CUSTOM_QUESTION:"<question>"
		SecurityQuestion *string `json:"securityQuestion,omitempty"`

		// ServerUrl Informatica Intelligent Cloud Services URL for the organization the user belongs
		// to. Use the serverUrl as a base for most version 2 REST API resource URIs.
		ServerUrl *string `json:"serverUrl,omitempty"`

		// SfUsername Salesforce user name. Included when user is configured to authenticate through Salesforce.
		SfUsername *string `json:"sfUsername,omitempty"`

		// SpiUrl This field is no longer applicable and has been deprecated.
		// Deprecated:
		SpiUrl *string `json:"spiUrl,omitempty"`

		// Timezone Time zone of the user. Time zone honors Daylight Saving Time.
		// For more information, see Time zone codes.
		Timezone *string `json:"timezone,omitempty"`

		// Title Title of the user.
		Title *string `json:"title,omitempty"`

		// UpdateTime When the user account was last updated.
		UpdateTime *string `json:"updateTime,omitempty"`

		// UpdatedBy Informatica Intelligent Cloud Services user who last updated the user account.
		UpdatedBy *string `json:"updatedBy,omitempty"`

		// UuId Unique identifier for the user.
		UuId *string `json:"uuId,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r LoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAgentInstallerInfoWithResponse request returning *GetAgentInstallerInfoResponse
func (c *ClientWithResponses) GetAgentInstallerInfoWithResponse(ctx context.Context, platform string, reqEditors ...RequestEditorFn) (*GetAgentInstallerInfoResponse, error) {
	rsp, err := c.GetAgentInstallerInfo(ctx, platform, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAgentInstallerInfoResponse(rsp)
}

// LoginWithBodyWithResponse request with arbitrary body returning *LoginResponse
func (c *ClientWithResponses) LoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LoginResponse, error) {
	rsp, err := c.LoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginResponse(rsp)
}

func (c *ClientWithResponses) LoginWithResponse(ctx context.Context, body LoginJSONRequestBody, reqEditors ...RequestEditorFn) (*LoginResponse, error) {
	rsp, err := c.Login(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginResponse(rsp)
}

// ParseGetAgentInstallerInfoResponse parses an HTTP response from a GetAgentInstallerInfoWithResponse call
func ParseGetAgentInstallerInfoResponse(rsp *http.Response) (*GetAgentInstallerInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAgentInstallerInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Type                *string `json:"@type,omitempty"`
			ChecksumDownloadUrl *string `json:"checksumDownloadUrl,omitempty"`
			DownloadUrl         *string `json:"downloadUrl,omitempty"`
			InstallToken        *string `json:"installToken,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseLoginResponse parses an HTTP response from a LoginWithResponse call
func ParseLoginResponse(rsp *http.Response) (*LoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// CreateTime When the user account was created.
			CreateTime *string `json:"createTime,omitempty"`

			// CreatedBy Informatica Intelligent Cloud Services user who created the user account.
			CreatedBy *string `json:"createdBy,omitempty"`

			// Description Description of the user.
			Description *string `json:"description,omitempty"`

			// Emails Email address to be notified when the user changes the account password.
			Emails *string `json:"emails,omitempty"`

			// FirstName First name for the user account.
			FirstName *string `json:"firstName,omitempty"`

			// ForceChangePassword Determines if the user must reset the password after the user logs in for the first time. Includes the following values:
			// True. The user must reset the password.
			// False. The user is not forced to reset the password.
			ForceChangePassword *bool `json:"forceChangePassword,omitempty"`

			// IcSessionId Informatica Intelligent Cloud Services session ID for version 2 REST API session.
			// Use in most version 2 REST API request headers.
			IcSessionId *string `json:"icSessionId,omitempty"`

			// Id User ID.
			Id *string `json:"id,omitempty"`

			// LastName Last name for the user account.
			LastName *string `json:"lastName,omitempty"`

			// Name Informatica Intelligent Cloud Services user name.
			Name *string `json:"name,omitempty"`

			// OrgId ID of the organization the user belongs to. 22 characters.
			// NOTE: Organizations that were created in legacy Informatica Cloud might have an
			// organization ID of 6 characters.
			OrgId *string `json:"orgId,omitempty"`

			// OrgUuid Unique identifier for the organization.
			OrgUuid *string `json:"orgUuid,omitempty"`

			// Password Salesforce user password. Included when user is configured to authenticate through Salesforce.
			Password *string `json:"password,omitempty"`

			// Phone Phone number for the user.
			Phone *string `json:"phone,omitempty"`

			// Roles Object that includes a role object for each role assigned to the user.
			Roles *struct {
				// Description Role description.
				Description *string `json:"description,omitempty"`

				// Name Role name. Returns one of the following codes:
				// Service Consumer
				// Designer
				// Admin
				Name *string `json:"name,omitempty"`
			} `json:"roles,omitempty"`

			// SecurityAnswer Answer to the security question.
			SecurityAnswer *string `json:"securityAnswer,omitempty"`

			// SecurityQuestion Security question. Returns one of the following codes:
			// SPOUSE_MEETING_CITY
			// FIRST_JOB_CITY
			// CHILDHOOD_FRIEND
			// MOTHER_MAIDEN_NAME
			// PET_NAME
			// CHILDHOOD_NICKNAME
			// CUSTOM_QUESTION:"<question>"
			SecurityQuestion *string `json:"securityQuestion,omitempty"`

			// ServerUrl Informatica Intelligent Cloud Services URL for the organization the user belongs
			// to. Use the serverUrl as a base for most version 2 REST API resource URIs.
			ServerUrl *string `json:"serverUrl,omitempty"`

			// SfUsername Salesforce user name. Included when user is configured to authenticate through Salesforce.
			SfUsername *string `json:"sfUsername,omitempty"`

			// SpiUrl This field is no longer applicable and has been deprecated.
			// Deprecated:
			SpiUrl *string `json:"spiUrl,omitempty"`

			// Timezone Time zone of the user. Time zone honors Daylight Saving Time.
			// For more information, see Time zone codes.
			Timezone *string `json:"timezone,omitempty"`

			// Title Title of the user.
			Title *string `json:"title,omitempty"`

			// UpdateTime When the user account was last updated.
			UpdateTime *string `json:"updateTime,omitempty"`

			// UpdatedBy Informatica Intelligent Cloud Services user who last updated the user account.
			UpdatedBy *string `json:"updatedBy,omitempty"`

			// UuId Unique identifier for the user.
			UuId *string `json:"uuId,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RYTW/bOBP+KwOeBTtI0ffg05vGTqvdxE79gcWiLgJaGktspaFKUvGmgf/7YijJlmO5",
	"SbPtKRU9nM9nnhn2UUQ6LzQhOSsGj9tAKFprMXgUTrkMxUBcxLkiuLgNYa0NhMObSxGIezRWaRIDcd47",
	"652JbSB0gSQLJQbijT8KRCFdykpFXxaqf3/elwmS6yuyTmYZmpDWuv9YZNKttcm3LJmg4z8x2siowlUm",
	"5hoMfivROpAE9XVw+isSWA0ulQ4edAmRJOBoMnQILkWYYVQahAs2CwYTZZ2RrBQKoyO0FrQBpyFB5+Wj",
	"FKOvtsxBr/2397cxuLuYGJkLH2+lLIzFQLxH582E7eB8DozM0aGxYvDpUSiOh/MiAkEy5/w28YtA2CjF",
	"XHYkIEVoxHwV2Lkut3oiEO6hYLXWGUWJ2G4/B8KgLTRZ9MU4PzvjP5Emh+SzLYsiU5FX1P9i2eJjy5XC",
	"cKROVbf/X6l/fGomEE3yhnpDmZbxwmSdcvEzv9dxzbm8HQLbXYR69QUjJ7Z8dJivC7BlxPVdl9kOOgZd",
	"acj63DU+wGJ6HRwiKgBJ8R4Jbcke29oGop/LBtGlRdPPdKK8q4W2PqGH0Lj2P3MVvCPvdPzwWwpQSGs3",
	"2sTH+GEsmlw6FUkIyWGWKY/sy0yXMczQ3KsILTQKGEW5/OcaKXGpGJy/fRscW+PIKwS/0horANawQ7Q2",
	"iST1vUL0rqs3khw3aaYTUAROv8C9bZVtZTAWg097X1tJ+tyBo+0vbZXIoHQ4V105+itF8jH7LMgo0iU5",
	"2EgL1a24o5ODWmP87uG/JX2T6sbMkQ+ddg9MPbU83H81vMkKOxVhLlVmj3WM+BxkHBsmZadhhUDaqbXC",
	"GDYHuYpSSQlWbdzkrQ3cI5trZawbdyL1in86xOCzuVhrE+Gld+L2ZMMNmfFzRWhB7VMCeel5yNbjpnEb",
	"5Nphy3ymE8tQb3zyEYBTOfYgpCgr4zr+tc4yvVGUwL3MSrSDJc1NiT2YP2Oxt6Qrmdm2pLKccfDhxVyC",
	"jlv7fKy0zlCS5+tohtbWZPdKWNpKA4RDH3S9XcA5TEezud89aonekhaWZx/k2rouwYbuU5QxGttZQ9Xh",
	"6YKTEA475TN5CkHX8qcB9GtIs1O1NklnEYZNYz5h2NrbFWaaEu67Hpyfc4cZGfHK0lvSeDIfDWDSumcr",
	"at6gwR2LKIIMExk9QDuOyvdcJamDVN4jSFrSgQuVZ/9rmzwR16LsLBqpbyWCipE8WZjOWdKp8/S0nMkM",
	"re+DKj07+DfNV1NS0zaRprVKSlO1jSxdyt5E0i+hRpdJCnuV3b6kmjowccvHQGW+agV2kluNzrCDWid+",
	"ulU1Uw15SGBpqCafV40ySqtDaa1KqAqmbfBwuP1wJExZT+voJ/rAX/UAh2m9sHESavzuCS/Ssee7ujPg",
	"UpMtczRLGqL33yzJv1xE8PwGGQjLLwXlHi7IbtAcu1WdNylppMFTzakAG6mPtVAH0o70vDDo28liNrq7",
	"GY3m4fj93WU4/3tJV+F0Nr/7Y/Ku/r78EF4PP0wmw7uraTgaD5d0M5l/GE3vbi7C4Wh8N764GS3pdjSv",
	"/7WXH4eXf9Zni9l8cnP3cTGazcPJeLAUy/Ls7E3U+Ou/cCm6wzf3aOot/1Vkt5hen9oND5lrSUxdPBiq",
	"6tSGQTLSV9JW7Hx6YlhdcrcvpmE3/9j14uS2+5QtKuz+LqawhdpltDDIV2MxcKbE4OjNqCysFWZxNdqB",
	"M8WjqdpgV9zpFEMqLawQCfb6Og3z9vG9k6V4wYXvLbx6woD9capJGwtD+ZD5UTCT9wxmFuA9xFfG8Eyv",
	"QaEpAIvY0uBxf8It/58Uxz65DJ/dRssifsWCzssAVFfjH6j9JVt629bLtouyDH9qTp5Izkte2dPWg9r7",
	"VY+TeuNtFjFlW6/x6gm93f4bAAD//8zZ1p93EgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
