// <editor-fold desc="imports" defaultstate="collapsed"> ///////////////////////

// Package v3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v3

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="constants" defaultstate="collapsed"> /////////////////////

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="constants" defaultstate="collapsed"> /////////////////////

// Defines values for LoginResponseBodyUserInfoStatus.
const (
	LoginResponseBodyUserInfoStatusActive   LoginResponseBodyUserInfoStatus = "Active"
	LoginResponseBodyUserInfoStatusInactive LoginResponseBodyUserInfoStatus = "Inactive"
)

// Defines values for RolePrivilegeItemStatus.
const (
	RolePrivilegeItemStatusDefault    RolePrivilegeItemStatus = "Default"
	RolePrivilegeItemStatusDisabled   RolePrivilegeItemStatus = "Disabled"
	RolePrivilegeItemStatusEnabled    RolePrivilegeItemStatus = "Enabled"
	RolePrivilegeItemStatusUnassigned RolePrivilegeItemStatus = "Unassigned"
)

// Defines values for RoleStatus.
const (
	RoleStatusDisabled RoleStatus = "Disabled"
	RoleStatusEnabled  RoleStatus = "Enabled"
)

// Defines values for GetRolesParamsExpand.
const (
	GetRolesParamsExpandPrivileges GetRolesParamsExpand = "privileges"
)

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="typedef" defaultstate="collapsed"> ///////////////////////

// ApiError defines model for apiError.
type ApiError struct {
	Code         string            `json:"code"`
	DebugMessage *string           `json:"debugMessage,omitempty"`
	Details      *[]ApiErrorDetail `json:"details,omitempty"`
	Message      string            `json:"message"`
	RequestId    string            `json:"requestId"`
}

// ApiErrorDetail defines model for apiErrorDetail.
type ApiErrorDetail struct {
	Code         string  `json:"code"`
	DebugMessage *string `json:"debugMessage,omitempty"`
	Message      string  `json:"message"`
}

// ApiErrorResponseBody When the REST API encounters an error, it returns a REST API error object.
type ApiErrorResponseBody struct {
	Error ApiError `json:"error"`
}

// CreateRoleRequestBody defines model for createRoleRequestBody.
type CreateRoleRequestBody struct {
	// Description Description of the role.
	Description *string `json:"description,omitempty"`

	// Name Name of the role.
	Name *string `json:"name,omitempty"`

	// Privileges IDs of the privileges to assign to the role.
	// A role must have at least one privilege assigned to it.
	Privileges *[]string `json:"privileges,omitempty"`
}

// CreateRoleResponseBody defines model for createRoleResponseBody.
type CreateRoleResponseBody struct {
	// CreateTime Date and time the role was created.
	CreateTime *string `json:"createTime,omitempty"`

	// CreatedBy User who created the role.
	CreatedBy *string `json:"createdBy,omitempty"`

	// Description Description of the role.
	Description *string `json:"description,omitempty"`

	// DisplayDescription Description displayed in the user interface.
	DisplayDescription *string `json:"displayDescription,omitempty"`

	// DisplayName Role name displayed in the user interface.
	DisplayName *string `json:"displayName,omitempty"`

	// Id Role ID.
	Id *string `json:"id,omitempty"`

	// OrgId ID of the organization the role belongs to.
	OrgId      *string              `json:"orgId,omitempty"`
	Privileges *[]RolePrivilegeItem `json:"privileges,omitempty"`

	// RoleName Name of the role.
	RoleName *string `json:"roleName,omitempty"`

	// Status Whether the organization's license to use the role is valid or has expired.
	Status *RoleStatus `json:"status,omitempty"`

	// SystemRole Whether the role is a system-defined role.
	SystemRole *bool `json:"systemRole,omitempty"`

	// UpdateTime Date and time the role was last updated.
	UpdateTime *string `json:"updateTime,omitempty"`

	// UpdatedBy User who last updated the role.
	UpdatedBy *string `json:"updatedBy,omitempty"`
}

// GetRolesResponseBody defines model for getRolesResponseBody.
type GetRolesResponseBody = []GetRolesResponseBodyItem

// GetRolesResponseBodyItem defines model for getRolesResponseBodyItem.
type GetRolesResponseBodyItem struct {
	// CreateTime Date and time the role was created.
	CreateTime *string `json:"createTime,omitempty"`

	// CreatedBy User who created the role.
	CreatedBy *string `json:"createdBy,omitempty"`

	// Description Description of the role.
	Description *string `json:"description,omitempty"`

	// DisplayDescription Description displayed in the user interface.
	DisplayDescription *string `json:"displayDescription,omitempty"`

	// DisplayName Role name displayed in the user interface.
	DisplayName *string `json:"displayName,omitempty"`

	// Id Role ID.
	Id *string `json:"id,omitempty"`

	// OrgId ID of the organization the role belongs to.
	OrgId      *string              `json:"orgId,omitempty"`
	Privileges *[]RolePrivilegeItem `json:"privileges,omitempty"`

	// RoleName Name of the role.
	RoleName *string `json:"roleName,omitempty"`

	// Status Whether the organization's license to use the role is valid or has expired.
	Status *RoleStatus `json:"status,omitempty"`

	// SystemRole Whether the role is a system-defined role.
	SystemRole *bool `json:"systemRole,omitempty"`

	// UpdateTime Date and time the role was last updated.
	UpdateTime *string `json:"updateTime,omitempty"`

	// UpdatedBy User who last updated the role.
	UpdatedBy *string `json:"updatedBy,omitempty"`
}

// LoginRequestBody defines model for loginRequestBody.
type LoginRequestBody struct {
	// Password Informatica Intelligent Cloud Services password.
	Password string `json:"password"`

	// Username Informatica Intelligent Cloud Services user name for the organization that you want to log in to.
	Username string `json:"username"`
}

// LoginResponseBody defines model for loginResponseBody.
type LoginResponseBody struct {
	// Products Subscribed Informatica products.
	Products *[]LoginResponseBodyProduct `json:"products,omitempty"`
	UserInfo *LoginResponseBodyUserInfo  `json:"userInfo,omitempty"`
}

// LoginResponseBodyProduct defines model for loginResponseBodyProduct.
type LoginResponseBodyProduct struct {
	// BaseApiUrl Base API URL for the product. Use in REST API requests.
	BaseApiUrl *string `json:"baseApiUrl,omitempty"`

	// Name Product name.
	Name *string `json:"name,omitempty"`
}

// LoginResponseBodyUserInfo defines model for loginResponseBodyUserInfo.
type LoginResponseBodyUserInfo struct {
	// Groups User group information for the user.
	Groups *map[string]interface{} `json:"groups,omitempty"`

	// Id User ID.
	Id *string `json:"id,omitempty"`

	// Name User name.
	Name *string `json:"name,omitempty"`

	// OrgId ID of the organization the user belongs to.
	OrgId *string `json:"orgId,omitempty"`

	// OrgName Organization name.
	OrgName *string `json:"orgName,omitempty"`

	// ParentOrgId Organization ID for the parent.
	ParentOrgId *string `json:"parentOrgId,omitempty"`

	// SessionId REST API session ID for the current session. Use in most REST API request headers.
	SessionId *string `json:"sessionId,omitempty"`

	// Status Status of the user.
	Status *LoginResponseBodyUserInfoStatus `json:"status,omitempty"`
}

// LoginResponseBodyUserInfoStatus Status of the user.
type LoginResponseBodyUserInfoStatus string

// RoleInfo defines model for roleInfo.
type RoleInfo struct {
	// CreateTime Date and time the role was created.
	CreateTime *string `json:"createTime,omitempty"`

	// CreatedBy User who created the role.
	CreatedBy *string `json:"createdBy,omitempty"`

	// Description Description of the role.
	Description *string `json:"description,omitempty"`

	// DisplayDescription Description displayed in the user interface.
	DisplayDescription *string `json:"displayDescription,omitempty"`

	// DisplayName Role name displayed in the user interface.
	DisplayName *string `json:"displayName,omitempty"`

	// Id Role ID.
	Id *string `json:"id,omitempty"`

	// OrgId ID of the organization the role belongs to.
	OrgId *string `json:"orgId,omitempty"`

	// RoleName Name of the role.
	RoleName *string `json:"roleName,omitempty"`

	// Status Whether the organization's license to use the role is valid or has expired.
	Status *RoleStatus `json:"status,omitempty"`

	// SystemRole Whether the role is a system-defined role.
	SystemRole *bool `json:"systemRole,omitempty"`

	// UpdateTime Date and time the role was last updated.
	UpdateTime *string `json:"updateTime,omitempty"`

	// UpdatedBy User who last updated the role.
	UpdatedBy *string `json:"updatedBy,omitempty"`
}

// RolePrivilegeItem defines model for rolePrivilegeItem.
type RolePrivilegeItem struct {
	// Description Description of the privilege.
	Description *string `json:"description,omitempty"`

	// Id Privilege ID.
	Id string `json:"id"`

	// Name Name of the privilege.
	Name string `json:"name"`

	// Service The Informatica Intelligent Cloud Services service that applies to the privilege.
	Service string `json:"service"`

	// Status Status of the privilege. Returns one of the following values:
	// * Enabled: License to use the privilege is valid.
	// * Disabled: License to use the privilege has expired.
	// * Unassigned: No license to use this privilege.
	// * Default: Privilege included by default.
	Status RolePrivilegeItemStatus `json:"status"`
}

// RolePrivilegeItemStatus Status of the privilege. Returns one of the following values:
// * Enabled: License to use the privilege is valid.
// * Disabled: License to use the privilege has expired.
// * Unassigned: No license to use this privilege.
// * Default: Privilege included by default.
type RolePrivilegeItemStatus string

// RoleStatus Whether the organization's license to use the role is valid or has expired.
type RoleStatus string

// UpdateRoleRequestBody defines model for updateRoleRequestBody.
type UpdateRoleRequestBody struct {
	// Privileges IDs of the privileges to assign to the role.
	// A role must have at least one privilege assigned to it.
	Privileges []string `json:"privileges"`
}

// WithPrivilegeItems defines model for withPrivilegeItems.
type WithPrivilegeItems struct {
	Privileges *[]RolePrivilegeItem `json:"privileges,omitempty"`
}

// WithPrivilegeRefs defines model for withPrivilegeRefs.
type WithPrivilegeRefs struct {
	// Privileges IDs of the privileges to assign to the role.
	// A role must have at least one privilege assigned to it.
	Privileges *[]string `json:"privileges,omitempty"`
}

// HeaderSession defines model for headerSession.
type HeaderSession = string

// PathRole defines model for pathRole.
type PathRole = string

// N204 When the REST API encounters an error, it returns a REST API error object.
type N204 = ApiErrorResponseBody

// N400 When the REST API encounters an error, it returns a REST API error object.
type N400 = ApiErrorResponseBody

// N401 When the REST API encounters an error, it returns a REST API error object.
type N401 = ApiErrorResponseBody

// N403 When the REST API encounters an error, it returns a REST API error object.
type N403 = ApiErrorResponseBody

// N404 When the REST API encounters an error, it returns a REST API error object.
type N404 = ApiErrorResponseBody

// N500 When the REST API encounters an error, it returns a REST API error object.
type N500 = ApiErrorResponseBody

// N502 When the REST API encounters an error, it returns a REST API error object.
type N502 = ApiErrorResponseBody

// N503 When the REST API encounters an error, it returns a REST API error object.
type N503 = ApiErrorResponseBody

// RolePrivileges defines model for rolePrivileges.
type RolePrivileges = UpdateRoleRequestBody

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="param-types" defaultstate="collapsed"> ///////////////////

// ListPrivilegesParams defines parameters for ListPrivileges.
type ListPrivilegesParams struct {
	// Q The query string used to filter results.
	Q *string `json:"q,omitempty"`
}

// GetRolesParams defines parameters for GetRoles.
type GetRolesParams struct {
	// Q Query filter. You can filter using one of the following fields:
	// * roleId. Unique identifier for the role.
	// * roleName. Name of the role.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Expand Returns the privileges associated with the role specified in the query filter.
	Expand        *GetRolesParamsExpand `form:"expand,omitempty" json:"expand,omitempty"`
	INFASESSIONID HeaderSession         `json:"INFA-SESSION-ID"`
}

// GetRolesParamsExpand defines parameters for GetRoles.
type GetRolesParamsExpand string

// DeleteRoleParams defines parameters for DeleteRole.
type DeleteRoleParams struct {
	INFASESSIONID HeaderSession `json:"INFA-SESSION-ID"`
}

// AddRolePrivilegesParams defines parameters for AddRolePrivileges.
type AddRolePrivilegesParams struct {
	INFASESSIONID HeaderSession `json:"INFA-SESSION-ID"`
}

// RemoveRolePrivilegesParams defines parameters for RemoveRolePrivileges.
type RemoveRolePrivilegesParams struct {
	INFASESSIONID HeaderSession `json:"INFA-SESSION-ID"`
}

// </editor-fold> //////////////////////////////////////////////////////////////

// <editor-fold desc="request-bodies" defaultstate="collapsed"> ////////////////

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequestBody

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = CreateRoleRequestBody

// AddRolePrivilegesJSONRequestBody defines body for AddRolePrivileges for application/json ContentType.
type AddRolePrivilegesJSONRequestBody = UpdateRoleRequestBody

// RemoveRolePrivilegesJSONRequestBody defines body for RemoveRolePrivileges for application/json ContentType.
type RemoveRolePrivilegesJSONRequestBody = UpdateRoleRequestBody

// </editor-fold> //////////////////////////////////////////////////////////////

// <editor-fold desc="additional-properties" defaultstate="collapsed"> /////////

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="additional-properties" defaultstate="collapsed"> /////////

// </editor-fold> //////////////////////////////////////////////////////////////
