// <editor-fold desc="imports" defaultstate="collapsed"> ///////////////////////

// Package v3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v3

import (
	"github.com/oapi-codegen/nullable"
)

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="constants" defaultstate="collapsed"> /////////////////////

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="constants" defaultstate="collapsed"> /////////////////////

// Defines values for CreateUserRequestBodyAuthentication.
const (
	CreateUserRequestBodyAuthenticationN0 CreateUserRequestBodyAuthentication = 0
	CreateUserRequestBodyAuthenticationN1 CreateUserRequestBodyAuthentication = 1
)

// Defines values for LoginResponseBodyUserInfoStatus.
const (
	LoginResponseBodyUserInfoStatusActive   LoginResponseBodyUserInfoStatus = "Active"
	LoginResponseBodyUserInfoStatusInactive LoginResponseBodyUserInfoStatus = "Inactive"
)

// Defines values for RolePrivilegeItemStatus.
const (
	RolePrivilegeItemStatusDefault    RolePrivilegeItemStatus = "Default"
	RolePrivilegeItemStatusDisabled   RolePrivilegeItemStatus = "Disabled"
	RolePrivilegeItemStatusEnabled    RolePrivilegeItemStatus = "Enabled"
	RolePrivilegeItemStatusUnassigned RolePrivilegeItemStatus = "Unassigned"
)

// Defines values for RoleStatus.
const (
	RoleStatusDisabled RoleStatus = "Disabled"
	RoleStatusEnabled  RoleStatus = "Enabled"
)

// Defines values for UserDetailsAuthentication.
const (
	UserDetailsAuthenticationN0 UserDetailsAuthentication = 0
	UserDetailsAuthenticationN1 UserDetailsAuthentication = 1
)

// Defines values for UserDetailsState.
const (
	UserDetailsStateActive      UserDetailsState = "Active"
	UserDetailsStateDisabled    UserDetailsState = "Disabled"
	UserDetailsStateProvisioned UserDetailsState = "Provisioned"
)

// Defines values for UserDetailsEditableAuthentication.
const (
	UserDetailsEditableAuthenticationN0 UserDetailsEditableAuthentication = 0
	UserDetailsEditableAuthenticationN1 UserDetailsEditableAuthentication = 1
)

// Defines values for GetRolesParamsExpand.
const (
	GetRolesParamsExpandPrivileges GetRolesParamsExpand = "privileges"
)

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="typedef" defaultstate="collapsed"> ///////////////////////

// ApiError defines model for apiError.
type ApiError struct {
	Code         string            `json:"code"`
	DebugMessage *string           `json:"debugMessage,omitempty"`
	Details      *[]ApiErrorDetail `json:"details,omitempty"`
	Message      string            `json:"message"`
	RequestId    string            `json:"requestId"`
}

// ApiErrorDetail defines model for apiErrorDetail.
type ApiErrorDetail struct {
	Code         string  `json:"code"`
	DebugMessage *string `json:"debugMessage,omitempty"`
	Message      string  `json:"message"`
}

// ApiErrorResponseBody When the REST API encounters an error, it returns a REST API error object.
type ApiErrorResponseBody struct {
	Error ApiError `json:"error"`
}

// CreateRoleRequestBody defines model for createRoleRequestBody.
type CreateRoleRequestBody struct {
	// Description Description of the role.
	Description *string `json:"description,omitempty"`

	// Name Name of the role.
	Name *string `json:"name,omitempty"`

	// Privileges IDs of the privileges to assign to the role.
	// A role must have at least one privilege assigned to it.
	Privileges *[]string `json:"privileges,omitempty"`
}

// CreateRoleResponseBody defines model for createRoleResponseBody.
type CreateRoleResponseBody struct {
	// CreateTime Date and time the role was created.
	CreateTime *string `json:"createTime,omitempty"`

	// CreatedBy User who created the role.
	CreatedBy *string `json:"createdBy,omitempty"`

	// Description Description of the role.
	Description *string `json:"description,omitempty"`

	// DisplayDescription Description displayed in the user interface.
	DisplayDescription *string `json:"displayDescription,omitempty"`

	// DisplayName Role name displayed in the user interface.
	DisplayName *string `json:"displayName,omitempty"`

	// Id Role ID.
	Id *string `json:"id,omitempty"`

	// OrgId ID of the organization the role belongs to.
	OrgId      *string              `json:"orgId,omitempty"`
	Privileges *[]RolePrivilegeItem `json:"privileges,omitempty"`

	// RoleName Name of the role.
	RoleName *string `json:"roleName,omitempty"`

	// Status Whether the organization's license to use the role is valid or has expired.
	Status *RoleStatus `json:"status,omitempty"`

	// SystemRole Whether the role is a system-defined role.
	SystemRole *bool `json:"systemRole,omitempty"`

	// UpdateTime Date and time the role was last updated.
	UpdateTime *string `json:"updateTime,omitempty"`

	// UpdatedBy User who last updated the role.
	UpdatedBy *string `json:"updatedBy,omitempty"`
}

// CreateUserRequestBody defines model for createUserRequestBody.
type CreateUserRequestBody struct {
	// AliasName The user identifier or user name in the 3rd party system.
	AliasName *string `json:"aliasName,omitempty"`

	// Authentication Determines whether the user accesses Informatica Intelligent Cloud Services through single sign-in (SAML).
	// Use one of the following values:
	// 0. Native.
	// 1. SAML.
	Authentication *CreateUserRequestBodyAuthentication `json:"authentication,omitempty"`

	// Description Description of the user.
	Description *string `json:"description,omitempty"`

	// Email Email address for the user.
	Email string `json:"email"`

	// FirstName First name for the user account.
	FirstName string `json:"firstName"`

	// ForcePasswordChange Determines whether the user must reset the password after the user logs in for the first time.
	ForcePasswordChange *bool `json:"forcePasswordChange,omitempty"`

	// Groups IDs of the user groups to assign to the user.
	Groups *[]string `json:"groups,omitempty"`

	// LastName Last name for the user account.
	LastName string `json:"lastName"`

	// MaxLoginAttempts Number of times a user can attempt to log in before the account is locked.
	MaxLoginAttempts *int `json:"maxLoginAttempts,omitempty"`

	// Name Informatica Intelligent Cloud Services user name.
	Name interface{} `json:"name"`

	// Password Informatica Intelligent Cloud Services password.
	// If password is empty, the user receives an activation email.
	// Maximum length is 255 characters.
	Password *string `json:"password,omitempty"`

	// Phone Phone number for the user.
	Phone nullable.Nullable[string] `json:"phone,omitempty"`

	// Roles IDs of the roles to assign to the user.
	Roles *[]string `json:"roles,omitempty"`

	// Title Job title of the user.
	Title *string `json:"title,omitempty"`
}

// CreateUserRequestBodyAuthentication Determines whether the user accesses Informatica Intelligent Cloud Services through single sign-in (SAML).
// Use one of the following values:
// 0. Native.
// 1. SAML.
type CreateUserRequestBodyAuthentication int

// GetRolesResponseBody defines model for getRolesResponseBody.
type GetRolesResponseBody = []GetRolesResponseBodyItem

// GetRolesResponseBodyItem defines model for getRolesResponseBodyItem.
type GetRolesResponseBodyItem struct {
	// CreateTime Date and time the role was created.
	CreateTime *string `json:"createTime,omitempty"`

	// CreatedBy User who created the role.
	CreatedBy *string `json:"createdBy,omitempty"`

	// Description Description of the role.
	Description *string `json:"description,omitempty"`

	// DisplayDescription Description displayed in the user interface.
	DisplayDescription *string `json:"displayDescription,omitempty"`

	// DisplayName Role name displayed in the user interface.
	DisplayName *string `json:"displayName,omitempty"`

	// Id Role ID.
	Id *string `json:"id,omitempty"`

	// OrgId ID of the organization the role belongs to.
	OrgId      *string              `json:"orgId,omitempty"`
	Privileges *[]RolePrivilegeItem `json:"privileges,omitempty"`

	// RoleName Name of the role.
	RoleName *string `json:"roleName,omitempty"`

	// Status Whether the organization's license to use the role is valid or has expired.
	Status *RoleStatus `json:"status,omitempty"`

	// SystemRole Whether the role is a system-defined role.
	SystemRole *bool `json:"systemRole,omitempty"`

	// UpdateTime Date and time the role was last updated.
	UpdateTime *string `json:"updateTime,omitempty"`

	// UpdatedBy User who last updated the role.
	UpdatedBy *string `json:"updatedBy,omitempty"`
}

// GetUserResponseBody defines model for getUserResponseBody.
type GetUserResponseBody = []UserDetails

// LoginRequestBody defines model for loginRequestBody.
type LoginRequestBody struct {
	// Password Informatica Intelligent Cloud Services password.
	Password string `json:"password"`

	// Username Informatica Intelligent Cloud Services user name for the organization that you want to log in to.
	Username string `json:"username"`
}

// LoginResponseBody defines model for loginResponseBody.
type LoginResponseBody struct {
	// Products Subscribed Informatica products.
	Products []LoginResponseBodyProduct `json:"products"`
	UserInfo LoginResponseBodyUserInfo  `json:"userInfo"`
}

// LoginResponseBodyProduct defines model for loginResponseBodyProduct.
type LoginResponseBodyProduct struct {
	// BaseApiUrl Base API URL for the product. Use in REST API requests.
	BaseApiUrl string `json:"baseApiUrl"`

	// Name Product name.
	Name string `json:"name"`
}

// LoginResponseBodyUserInfo defines model for loginResponseBodyUserInfo.
type LoginResponseBodyUserInfo struct {
	// Groups User group information for the user.
	Groups map[string]interface{} `json:"groups"`

	// Id User ID.
	Id string `json:"id"`

	// Name User name.
	Name string `json:"name"`

	// OrgId ID of the organization the user belongs to.
	OrgId string `json:"orgId"`

	// OrgName Organization name.
	OrgName string `json:"orgName"`

	// ParentOrgId Organization ID for the parent.
	ParentOrgId string `json:"parentOrgId"`

	// SessionId REST API session ID for the current session. Use in most REST API request headers.
	SessionId string `json:"sessionId"`

	// Status Status of the user.
	Status LoginResponseBodyUserInfoStatus `json:"status"`
}

// LoginResponseBodyUserInfoStatus Status of the user.
type LoginResponseBodyUserInfoStatus string

// RoleInfo defines model for roleInfo.
type RoleInfo struct {
	// CreateTime Date and time the role was created.
	CreateTime *string `json:"createTime,omitempty"`

	// CreatedBy User who created the role.
	CreatedBy *string `json:"createdBy,omitempty"`

	// Description Description of the role.
	Description *string `json:"description,omitempty"`

	// DisplayDescription Description displayed in the user interface.
	DisplayDescription *string `json:"displayDescription,omitempty"`

	// DisplayName Role name displayed in the user interface.
	DisplayName *string `json:"displayName,omitempty"`

	// Id Role ID.
	Id *string `json:"id,omitempty"`

	// OrgId ID of the organization the role belongs to.
	OrgId *string `json:"orgId,omitempty"`

	// RoleName Name of the role.
	RoleName *string `json:"roleName,omitempty"`

	// Status Whether the organization's license to use the role is valid or has expired.
	Status *RoleStatus `json:"status,omitempty"`

	// SystemRole Whether the role is a system-defined role.
	SystemRole *bool `json:"systemRole,omitempty"`

	// UpdateTime Date and time the role was last updated.
	UpdateTime *string `json:"updateTime,omitempty"`

	// UpdatedBy User who last updated the role.
	UpdatedBy *string `json:"updatedBy,omitempty"`
}

// RoleNamesRequestBody defines model for roleNamesRequestBody.
type RoleNamesRequestBody struct {
	// Roles A list of role names.
	Roles []string `json:"roles"`
}

// RolePrivilegeItem defines model for rolePrivilegeItem.
type RolePrivilegeItem struct {
	// Description Description of the privilege.
	Description *string `json:"description,omitempty"`

	// Id Privilege ID.
	Id string `json:"id"`

	// Name Name of the privilege.
	Name string `json:"name"`

	// Service The Informatica Intelligent Cloud Services service that applies to the privilege.
	Service string `json:"service"`

	// Status Status of the privilege. Returns one of the following values:
	// * Enabled: License to use the privilege is valid.
	// * Disabled: License to use the privilege has expired.
	// * Unassigned: No license to use this privilege.
	// * Default: Privilege included by default.
	Status RolePrivilegeItemStatus `json:"status"`
}

// RolePrivilegeItemStatus Status of the privilege. Returns one of the following values:
// * Enabled: License to use the privilege is valid.
// * Disabled: License to use the privilege has expired.
// * Unassigned: No license to use this privilege.
// * Default: Privilege included by default.
type RolePrivilegeItemStatus string

// RoleStatus Whether the organization's license to use the role is valid or has expired.
type RoleStatus string

// UpdateRoleRequestBody defines model for updateRoleRequestBody.
type UpdateRoleRequestBody struct {
	// Privileges IDs of the privileges to assign to the role.
	// A role must have at least one privilege assigned to it.
	Privileges []string `json:"privileges"`
}

// UserDetails defines model for userDetails.
type UserDetails struct {
	// AliasName The user identifier or user name in the 3rd party system.
	AliasName *string `json:"aliasName,omitempty"`

	// Authentication Determines whether the user accesses Informatica Intelligent Cloud Services through single sign-in (SAML).
	// Use one of the following values:
	// 0. Native.
	// 1. SAML.
	Authentication UserDetailsAuthentication `json:"authentication"`

	// CreateTime The date and time of this resource's creation.
	CreateTime *string `json:"createTime,omitempty"`

	// CreatedBy The user this resource was created by.
	CreatedBy *string `json:"createdBy,omitempty"`

	// Description Description of the user.
	Description string `json:"description"`

	// Email Email address for the user.
	Email string `json:"email"`

	// FirstName First name for the user account.
	FirstName string `json:"firstName"`

	// ForcePasswordChange Determines whether the user must reset the password after the user logs in for the first time.
	ForcePasswordChange bool `json:"forcePasswordChange"`

	// Groups All the groups assigned to this user.
	Groups []UserDetailsGroup `json:"groups"`

	// Id The id assigned to the resource by IDMC.
	Id *string `json:"id,omitempty"`

	// LastLoginMode Whether the user logged in through a REST API call or through the UI.
	LastLoginMode *string `json:"lastLoginMode,omitempty"`

	// LastLoginTime The date and time that the user last logged in.
	LastLoginTime nullable.Nullable[string] `json:"lastLoginTime,omitempty"`

	// LastName Last name for the user account.
	LastName string `json:"lastName"`

	// MaxLoginAttempts Number of times a user can attempt to log in before the account is locked.
	MaxLoginAttempts int `json:"maxLoginAttempts"`

	// OrgId The id for the org the resource belongs to.
	OrgId *string `json:"orgId,omitempty"`

	// Phone Phone number for the user.
	Phone nullable.Nullable[string] `json:"phone"`

	// Roles All the roles assigned to this user.
	Roles []UserDetailsRole `json:"roles"`

	// State State of the user account. Returns one of the following values:
	// * Active. User account exists and user has activated the account.
	// * Provisioned. User account exists but the user has not activated the account.
	// * Disabled. User account is disabled because the user exceeded the maximum number of login attempts.
	// NOTE: If the user's password is expired, the value is null.
	State *UserDetailsState `json:"state,omitempty"`

	// TimeZoneId Time zone of the user.
	// For more information, see Time zone codes:
	// https://docs.informatica.com/integration-cloud/b2b-gateway/current-version/rest-api-reference/rest-api-codes/time-zone-codes.html
	TimeZoneId string `json:"timeZoneId"`

	// Title Job title of the user.
	Title string `json:"title"`

	// UpdateTime The date and time of this resource's last update.
	UpdateTime *string `json:"updateTime,omitempty"`

	// UpdatedBy The user this resource was last updated by.
	UpdatedBy *string `json:"updatedBy,omitempty"`

	// UserName Informatica Intelligent Cloud Services user name.
	UserName string `json:"userName"`
}

// UserDetailsAuthentication Determines whether the user accesses Informatica Intelligent Cloud Services through single sign-in (SAML).
// Use one of the following values:
// 0. Native.
// 1. SAML.
type UserDetailsAuthentication int

// UserDetailsState State of the user account. Returns one of the following values:
// * Active. User account exists and user has activated the account.
// * Provisioned. User account exists but the user has not activated the account.
// * Disabled. User account is disabled because the user exceeded the maximum number of login attempts.
// NOTE: If the user's password is expired, the value is null.
type UserDetailsState string

// UserDetailsEditable User details that are editable and common between create and fetch.
type UserDetailsEditable struct {
	// AliasName The user identifier or user name in the 3rd party system.
	AliasName *string `json:"aliasName,omitempty"`

	// Authentication Determines whether the user accesses Informatica Intelligent Cloud Services through single sign-in (SAML).
	// Use one of the following values:
	// 0. Native.
	// 1. SAML.
	Authentication *UserDetailsEditableAuthentication `json:"authentication,omitempty"`

	// Description Description of the user.
	Description *string `json:"description,omitempty"`

	// Email Email address for the user.
	Email string `json:"email"`

	// FirstName First name for the user account.
	FirstName string `json:"firstName"`

	// ForcePasswordChange Determines whether the user must reset the password after the user logs in for the first time.
	ForcePasswordChange *bool `json:"forcePasswordChange,omitempty"`

	// Groups IDs of the user groups to assign to the user.
	Groups *[]string `json:"groups,omitempty"`

	// LastName Last name for the user account.
	LastName string `json:"lastName"`

	// MaxLoginAttempts Number of times a user can attempt to log in before the account is locked.
	MaxLoginAttempts *int `json:"maxLoginAttempts,omitempty"`

	// Phone Phone number for the user.
	Phone nullable.Nullable[string] `json:"phone,omitempty"`

	// Roles IDs of the roles to assign to the user.
	Roles *[]string `json:"roles,omitempty"`

	// Title Job title of the user.
	Title *string `json:"title,omitempty"`
}

// UserDetailsEditableAuthentication Determines whether the user accesses Informatica Intelligent Cloud Services through single sign-in (SAML).
// Use one of the following values:
// 0. Native.
// 1. SAML.
type UserDetailsEditableAuthentication int

// UserDetailsGroup Full reference object for a group assigned to a user.
type UserDetailsGroup struct {
	// Description Description of the user group.
	Description string `json:"description"`

	// Id User group ID.
	Id string `json:"id"`

	// UserGroupName User group name.
	UserGroupName string `json:"userGroupName"`
}

// UserDetailsRole Full reference object for a role assigned to a user.
type UserDetailsRole struct {
	// Description Description of the role.
	Description string `json:"description"`

	// DisplayDescription Role description that is displayed in the user interface.
	DisplayDescription *string `json:"displayDescription,omitempty"`

	// DisplayName Role name that is displayed in the user interface.
	DisplayName *string `json:"displayName,omitempty"`

	// Id Role ID.
	Id string `json:"id"`

	// RoleName Role name.
	RoleName string `json:"roleName"`
}

// WithPrivilegeItems defines model for withPrivilegeItems.
type WithPrivilegeItems struct {
	Privileges *[]RolePrivilegeItem `json:"privileges,omitempty"`
}

// WithPrivilegeRefs defines model for withPrivilegeRefs.
type WithPrivilegeRefs struct {
	// Privileges IDs of the privileges to assign to the role.
	// A role must have at least one privilege assigned to it.
	Privileges *[]string `json:"privileges,omitempty"`
}

// GetUserLimit defines model for getUserLimit.
type GetUserLimit = int

// GetUserQuery defines model for getUserQuery.
type GetUserQuery = string

// GetUserSkip defines model for getUserSkip.
type GetUserSkip = int

// HeaderSession defines model for headerSession.
type HeaderSession = string

// PathRole defines model for pathRole.
type PathRole = string

// PathUserId defines model for pathUserId.
type PathUserId = string

// PathUserName defines model for pathUserName.
type PathUserName = string

// N204 When the REST API encounters an error, it returns a REST API error object.
type N204 = ApiErrorResponseBody

// N400 When the REST API encounters an error, it returns a REST API error object.
type N400 = ApiErrorResponseBody

// N401 When the REST API encounters an error, it returns a REST API error object.
type N401 = ApiErrorResponseBody

// N403 When the REST API encounters an error, it returns a REST API error object.
type N403 = ApiErrorResponseBody

// N404 When the REST API encounters an error, it returns a REST API error object.
type N404 = ApiErrorResponseBody

// N500 When the REST API encounters an error, it returns a REST API error object.
type N500 = ApiErrorResponseBody

// N502 When the REST API encounters an error, it returns a REST API error object.
type N502 = ApiErrorResponseBody

// N503 When the REST API encounters an error, it returns a REST API error object.
type N503 = ApiErrorResponseBody

// CreateUserRequest defines model for createUserRequest.
type CreateUserRequest = CreateUserRequestBody

// RoleNamesRequest defines model for roleNamesRequest.
type RoleNamesRequest = RoleNamesRequestBody

// RolePrivileges defines model for rolePrivileges.
type RolePrivileges = UpdateRoleRequestBody

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="param-types" defaultstate="collapsed"> ///////////////////

// ListPrivilegesParams defines parameters for ListPrivileges.
type ListPrivilegesParams struct {
	// Q The query string used to filter results.
	Q *string `json:"q,omitempty"`
}

// GetRolesParams defines parameters for GetRoles.
type GetRolesParams struct {
	// Q Query filter. You can filter using one of the following fields:
	// * roleId. Unique identifier for the role.
	// * roleName. Name of the role.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Expand Returns the privileges associated with the role specified in the query filter.
	Expand        *GetRolesParamsExpand `form:"expand,omitempty" json:"expand,omitempty"`
	INFASESSIONID HeaderSession         `json:"INFA-SESSION-ID"`
}

// GetRolesParamsExpand defines parameters for GetRoles.
type GetRolesParamsExpand string

// DeleteRoleParams defines parameters for DeleteRole.
type DeleteRoleParams struct {
	INFASESSIONID HeaderSession `json:"INFA-SESSION-ID"`
}

// AddRolePrivilegesParams defines parameters for AddRolePrivileges.
type AddRolePrivilegesParams struct {
	INFASESSIONID HeaderSession `json:"INFA-SESSION-ID"`
}

// RemoveRolePrivilegesParams defines parameters for RemoveRolePrivileges.
type RemoveRolePrivilegesParams struct {
	INFASESSIONID HeaderSession `json:"INFA-SESSION-ID"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	// Q Query filter. You can filter using one of the following fields:
	// * userId. Unique identifier for the user.
	// * userName. Informatica Intelligent Cloud Services user name.
	Q *GetUserQuery `json:"q,omitempty"`

	// Limit Maximum number of users to return.
	// Maximum of 200. Default is 100.
	Limit *GetUserLimit `json:"limit,omitempty"`

	// Skip Amount to offset the list of results.
	// Default is 0.
	Skip          *GetUserSkip  `json:"skip,omitempty"`
	INFASESSIONID HeaderSession `json:"INFA-SESSION-ID"`
}

// CreateUserParams defines parameters for CreateUser.
type CreateUserParams struct {
	INFASESSIONID HeaderSession `json:"INFA-SESSION-ID"`
}

// </editor-fold> //////////////////////////////////////////////////////////////

// <editor-fold desc="request-bodies" defaultstate="collapsed"> ////////////////

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequestBody

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = CreateRoleRequestBody

// AddRolePrivilegesJSONRequestBody defines body for AddRolePrivileges for application/json ContentType.
type AddRolePrivilegesJSONRequestBody = UpdateRoleRequestBody

// RemoveRolePrivilegesJSONRequestBody defines body for RemoveRolePrivileges for application/json ContentType.
type RemoveRolePrivilegesJSONRequestBody = UpdateRoleRequestBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequestBody

// AddUserRolesByNameJSONRequestBody defines body for AddUserRolesByName for application/json ContentType.
type AddUserRolesByNameJSONRequestBody = RoleNamesRequestBody

// RemoveUserRolesByNameJSONRequestBody defines body for RemoveUserRolesByName for application/json ContentType.
type RemoveUserRolesByNameJSONRequestBody = RoleNamesRequestBody

// AddUserRolesJSONRequestBody defines body for AddUserRoles for application/json ContentType.
type AddUserRolesJSONRequestBody = RoleNamesRequestBody

// RemoveUserRolesJSONRequestBody defines body for RemoveUserRoles for application/json ContentType.
type RemoveUserRolesJSONRequestBody = RoleNamesRequestBody

// </editor-fold> //////////////////////////////////////////////////////////////

// <editor-fold desc="additional-properties" defaultstate="collapsed"> /////////

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="additional-properties" defaultstate="collapsed"> /////////

// </editor-fold> //////////////////////////////////////////////////////////////
