// <editor-fold desc="imports" defaultstate="collapsed"> ///////////////////////

// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v2

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	common "terraform-provider-idmc/internal/idmc/common"

	"github.com/oapi-codegen/runtime"
)

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="client" defaultstate="collapsed"> ////////////////////////

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	common.ClientConfig
}

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...common.ClientOption) (*Client, error) {
	config, err := common.NewClientConfig(server, opts...)
	return &Client{*config}, err
}

var _ common.Client = &Client{}

func (c *Client) Config() *common.ClientConfig {
	return &c.ClientConfig
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAgentInstallerInfo request
	GetAgentInstallerInfo(ctx context.Context, platform string, editors ...common.ClientConfigEditor) (*http.Response, error)

	// ListRuntimeEnvironments request
	ListRuntimeEnvironments(ctx context.Context, editors ...common.ClientConfigEditor) (*http.Response, error)

	// CreateRuntimeEnvironmentWithBody request with any body
	CreateRuntimeEnvironmentWithBody(ctx context.Context, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*http.Response, error)

	CreateRuntimeEnvironment(ctx context.Context, body CreateRuntimeEnvironmentJSONRequestBody, editors ...common.ClientConfigEditor) (*http.Response, error)

	// DeleteRuntimeEnvironment request
	DeleteRuntimeEnvironment(ctx context.Context, id string, editors ...common.ClientConfigEditor) (*http.Response, error)

	// GetRuntimeEnvironment request
	GetRuntimeEnvironment(ctx context.Context, id string, editors ...common.ClientConfigEditor) (*http.Response, error)

	// UpdateRuntimeEnvironmentWithBody request with any body
	UpdateRuntimeEnvironmentWithBody(ctx context.Context, id string, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*http.Response, error)

	UpdateRuntimeEnvironment(ctx context.Context, id string, body UpdateRuntimeEnvironmentJSONRequestBody, editors ...common.ClientConfigEditor) (*http.Response, error)

	// LoginWithBody request with any body
	LoginWithBody(ctx context.Context, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*http.Response, error)

	Login(ctx context.Context, body LoginJSONRequestBody, editors ...common.ClientConfigEditor) (*http.Response, error)
}

func (c *Client) GetAgentInstallerInfo(ctx context.Context, platform string, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewGetAgentInstallerInfoRequest(c.Server, platform)
	})
}

func (c *Client) ListRuntimeEnvironments(ctx context.Context, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewListRuntimeEnvironmentsRequest(c.Server)
	})
}

func (c *Client) CreateRuntimeEnvironmentWithBody(ctx context.Context, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewCreateRuntimeEnvironmentRequestWithBody(c.Server, contentType, body)
	})
}

func (c *Client) CreateRuntimeEnvironment(ctx context.Context, body CreateRuntimeEnvironmentJSONRequestBody, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewCreateRuntimeEnvironmentRequest(c.Server, body)
	})
}

func (c *Client) DeleteRuntimeEnvironment(ctx context.Context, id string, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewDeleteRuntimeEnvironmentRequest(c.Server, id)
	})
}

func (c *Client) GetRuntimeEnvironment(ctx context.Context, id string, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewGetRuntimeEnvironmentRequest(c.Server, id)
	})
}

func (c *Client) UpdateRuntimeEnvironmentWithBody(ctx context.Context, id string, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewUpdateRuntimeEnvironmentRequestWithBody(c.Server, id, contentType, body)
	})
}

func (c *Client) UpdateRuntimeEnvironment(ctx context.Context, id string, body UpdateRuntimeEnvironmentJSONRequestBody, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewUpdateRuntimeEnvironmentRequest(c.Server, id, body)
	})
}

func (c *Client) LoginWithBody(ctx context.Context, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewLoginRequestWithBody(c.Server, contentType, body)
	})
}

func (c *Client) Login(ctx context.Context, body LoginJSONRequestBody, editors ...common.ClientConfigEditor) (*http.Response, error) {
	return c.HandleRequest(ctx, editors, func() (*http.Request, error) {
		return NewLoginRequest(c.Server, body)
	})
}

// NewGetAgentInstallerInfoRequest generates requests for GetAgentInstallerInfo
func NewGetAgentInstallerInfoRequest(server string, platform string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "platform", runtime.ParamLocationPath, platform)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/agent/installerInfo/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListRuntimeEnvironmentsRequest generates requests for ListRuntimeEnvironments
func NewListRuntimeEnvironmentsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/runtimeEnvironment")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateRuntimeEnvironmentRequest calls the generic CreateRuntimeEnvironment builder with application/json body
func NewCreateRuntimeEnvironmentRequest(server string, body CreateRuntimeEnvironmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRuntimeEnvironmentRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateRuntimeEnvironmentRequestWithBody generates requests for CreateRuntimeEnvironment with any type of body
func NewCreateRuntimeEnvironmentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/runtimeEnvironment")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteRuntimeEnvironmentRequest generates requests for DeleteRuntimeEnvironment
func NewDeleteRuntimeEnvironmentRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/runtimeEnvironment/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRuntimeEnvironmentRequest generates requests for GetRuntimeEnvironment
func NewGetRuntimeEnvironmentRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/runtimeEnvironment/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateRuntimeEnvironmentRequest calls the generic UpdateRuntimeEnvironment builder with application/json body
func NewUpdateRuntimeEnvironmentRequest(server string, id string, body UpdateRuntimeEnvironmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateRuntimeEnvironmentRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateRuntimeEnvironmentRequestWithBody generates requests for UpdateRuntimeEnvironment with any type of body
func NewUpdateRuntimeEnvironmentRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/runtimeEnvironment/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewLoginRequest calls the generic Login builder with application/json body
func NewLoginRequest(server string, body LoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewLoginRequestWithBody generates requests for Login with any type of body
func NewLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ma/api/v2/user/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// </editor-fold> //////////////////////////////////////////////////////////////
// <editor-fold desc="client-with-responses" defaultstate="collapsed"> /////////

// ClientWithResponses builds on Client to offer response payloads
type ClientWithResponses struct {
	*Client
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...common.ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAgentInstallerInfoWithResponse request
	GetAgentInstallerInfoWithResponse(ctx context.Context, platform string, editors ...common.ClientConfigEditor) (*GetAgentInstallerInfoResponse, error)

	// ListRuntimeEnvironmentsWithResponse request
	ListRuntimeEnvironmentsWithResponse(ctx context.Context, editors ...common.ClientConfigEditor) (*ListRuntimeEnvironmentsResponse, error)

	// CreateRuntimeEnvironmentWithBodyWithResponse request with any body
	CreateRuntimeEnvironmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*CreateRuntimeEnvironmentResponse, error)

	CreateRuntimeEnvironmentWithResponse(ctx context.Context, body CreateRuntimeEnvironmentJSONRequestBody, editors ...common.ClientConfigEditor) (*CreateRuntimeEnvironmentResponse, error)

	// DeleteRuntimeEnvironmentWithResponse request
	DeleteRuntimeEnvironmentWithResponse(ctx context.Context, id string, editors ...common.ClientConfigEditor) (*DeleteRuntimeEnvironmentResponse, error)

	// GetRuntimeEnvironmentWithResponse request
	GetRuntimeEnvironmentWithResponse(ctx context.Context, id string, editors ...common.ClientConfigEditor) (*GetRuntimeEnvironmentResponse, error)

	// UpdateRuntimeEnvironmentWithBodyWithResponse request with any body
	UpdateRuntimeEnvironmentWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*UpdateRuntimeEnvironmentResponse, error)

	UpdateRuntimeEnvironmentWithResponse(ctx context.Context, id string, body UpdateRuntimeEnvironmentJSONRequestBody, editors ...common.ClientConfigEditor) (*UpdateRuntimeEnvironmentResponse, error)

	// LoginWithBodyWithResponse request with any body
	LoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*LoginResponse, error)

	LoginWithResponse(ctx context.Context, body LoginJSONRequestBody, editors ...common.ClientConfigEditor) (*LoginResponse, error)
}

type GetAgentInstallerInfoResponse struct {
	common.ClientResponse
	JSON200 *GetAgentInstallerInfoResponseBody
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON500 *N500
	JSON502 *N502
	JSON503 *N503
}

type ListRuntimeEnvironmentsResponse struct {
	common.ClientResponse
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON500 *N500
	JSON502 *N502
	JSON503 *N503
}

type CreateRuntimeEnvironmentResponse struct {
	common.ClientResponse
	JSON200 *RuntimeEnvironment
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON500 *N500
	JSON502 *N502
	JSON503 *N503
}

type DeleteRuntimeEnvironmentResponse struct {
	common.ClientResponse
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON500 *N500
	JSON502 *N502
	JSON503 *N503
}

type GetRuntimeEnvironmentResponse struct {
	common.ClientResponse
	JSON200 *RuntimeEnvironment
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON500 *N500
	JSON502 *N502
	JSON503 *N503
}

type UpdateRuntimeEnvironmentResponse struct {
	common.ClientResponse
	JSON200 *RuntimeEnvironment
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON500 *N500
	JSON502 *N502
	JSON503 *N503
}

type LoginResponse struct {
	common.ClientResponse
	JSON200 *LoginResponseBody
	JSON400 *N400
	JSON401 *N401
	JSON403 *N403
	JSON404 *N404
	JSON500 *N500
	JSON502 *N502
	JSON503 *N503
}

// GetAgentInstallerInfoWithResponse request returning *GetAgentInstallerInfoResponse
func (c *ClientWithResponses) GetAgentInstallerInfoWithResponse(ctx context.Context, platform string, editors ...common.ClientConfigEditor) (*GetAgentInstallerInfoResponse, error) {
	rsp, err := c.GetAgentInstallerInfo(ctx, platform, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseGetAgentInstallerInfoResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

// ListRuntimeEnvironmentsWithResponse request returning *ListRuntimeEnvironmentsResponse
func (c *ClientWithResponses) ListRuntimeEnvironmentsWithResponse(ctx context.Context, editors ...common.ClientConfigEditor) (*ListRuntimeEnvironmentsResponse, error) {
	rsp, err := c.ListRuntimeEnvironments(ctx, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseListRuntimeEnvironmentsResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

// CreateRuntimeEnvironmentWithBodyWithResponse request with arbitrary body returning *CreateRuntimeEnvironmentResponse
func (c *ClientWithResponses) CreateRuntimeEnvironmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*CreateRuntimeEnvironmentResponse, error) {
	rsp, err := c.CreateRuntimeEnvironmentWithBody(ctx, contentType, body, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseCreateRuntimeEnvironmentResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

func (c *ClientWithResponses) CreateRuntimeEnvironmentWithResponse(ctx context.Context, body CreateRuntimeEnvironmentJSONRequestBody, editors ...common.ClientConfigEditor) (*CreateRuntimeEnvironmentResponse, error) {
	rsp, err := c.CreateRuntimeEnvironment(ctx, body, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseCreateRuntimeEnvironmentResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

// DeleteRuntimeEnvironmentWithResponse request returning *DeleteRuntimeEnvironmentResponse
func (c *ClientWithResponses) DeleteRuntimeEnvironmentWithResponse(ctx context.Context, id string, editors ...common.ClientConfigEditor) (*DeleteRuntimeEnvironmentResponse, error) {
	rsp, err := c.DeleteRuntimeEnvironment(ctx, id, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseDeleteRuntimeEnvironmentResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

// GetRuntimeEnvironmentWithResponse request returning *GetRuntimeEnvironmentResponse
func (c *ClientWithResponses) GetRuntimeEnvironmentWithResponse(ctx context.Context, id string, editors ...common.ClientConfigEditor) (*GetRuntimeEnvironmentResponse, error) {
	rsp, err := c.GetRuntimeEnvironment(ctx, id, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseGetRuntimeEnvironmentResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

// UpdateRuntimeEnvironmentWithBodyWithResponse request with arbitrary body returning *UpdateRuntimeEnvironmentResponse
func (c *ClientWithResponses) UpdateRuntimeEnvironmentWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*UpdateRuntimeEnvironmentResponse, error) {
	rsp, err := c.UpdateRuntimeEnvironmentWithBody(ctx, id, contentType, body, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseUpdateRuntimeEnvironmentResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

func (c *ClientWithResponses) UpdateRuntimeEnvironmentWithResponse(ctx context.Context, id string, body UpdateRuntimeEnvironmentJSONRequestBody, editors ...common.ClientConfigEditor) (*UpdateRuntimeEnvironmentResponse, error) {
	rsp, err := c.UpdateRuntimeEnvironment(ctx, id, body, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseUpdateRuntimeEnvironmentResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

// LoginWithBodyWithResponse request with arbitrary body returning *LoginResponse
func (c *ClientWithResponses) LoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, editors ...common.ClientConfigEditor) (*LoginResponse, error) {
	rsp, err := c.LoginWithBody(ctx, contentType, body, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseLoginResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

func (c *ClientWithResponses) LoginWithResponse(ctx context.Context, body LoginJSONRequestBody, editors ...common.ClientConfigEditor) (*LoginResponse, error) {
	rsp, err := c.Login(ctx, body, editors...)
	if err != nil {
		return nil, err
	}
	apiRes, err := ParseLoginResponse(rsp)
	if err != nil {
		return nil, err
	}
	editor := c.Editors.Merge(editors...)
	if err := editor.EditApiResponse(ctx, &apiRes.ClientResponse); err != nil {
		return nil, err
	}
	return apiRes, nil
}

// ParseGetAgentInstallerInfoResponse parses an HTTP response from a GetAgentInstallerInfoWithResponse call
func ParseGetAgentInstallerInfoResponse(rsp *http.Response) (*GetAgentInstallerInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAgentInstallerInfoResponse{
		ClientResponse: common.ClientResponse{
			Response: rsp,
			Body:     bodyBytes,
		},
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetAgentInstallerInfoResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest N502
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest N503
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListRuntimeEnvironmentsResponse parses an HTTP response from a ListRuntimeEnvironmentsWithResponse call
func ParseListRuntimeEnvironmentsResponse(rsp *http.Response) (*ListRuntimeEnvironmentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListRuntimeEnvironmentsResponse{
		ClientResponse: common.ClientResponse{
			Response: rsp,
			Body:     bodyBytes,
		},
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest N502
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest N503
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseCreateRuntimeEnvironmentResponse parses an HTTP response from a CreateRuntimeEnvironmentWithResponse call
func ParseCreateRuntimeEnvironmentResponse(rsp *http.Response) (*CreateRuntimeEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRuntimeEnvironmentResponse{
		ClientResponse: common.ClientResponse{
			Response: rsp,
			Body:     bodyBytes,
		},
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeEnvironment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest N502
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest N503
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseDeleteRuntimeEnvironmentResponse parses an HTTP response from a DeleteRuntimeEnvironmentWithResponse call
func ParseDeleteRuntimeEnvironmentResponse(rsp *http.Response) (*DeleteRuntimeEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteRuntimeEnvironmentResponse{
		ClientResponse: common.ClientResponse{
			Response: rsp,
			Body:     bodyBytes,
		},
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest N502
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest N503
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetRuntimeEnvironmentResponse parses an HTTP response from a GetRuntimeEnvironmentWithResponse call
func ParseGetRuntimeEnvironmentResponse(rsp *http.Response) (*GetRuntimeEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRuntimeEnvironmentResponse{
		ClientResponse: common.ClientResponse{
			Response: rsp,
			Body:     bodyBytes,
		},
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeEnvironment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest N502
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest N503
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseUpdateRuntimeEnvironmentResponse parses an HTTP response from a UpdateRuntimeEnvironmentWithResponse call
func ParseUpdateRuntimeEnvironmentResponse(rsp *http.Response) (*UpdateRuntimeEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateRuntimeEnvironmentResponse{
		ClientResponse: common.ClientResponse{
			Response: rsp,
			Body:     bodyBytes,
		},
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeEnvironment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest N502
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest N503
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseLoginResponse parses an HTTP response from a LoginWithResponse call
func ParseLoginResponse(rsp *http.Response) (*LoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoginResponse{
		ClientResponse: common.ClientResponse{
			Response: rsp,
			Body:     bodyBytes,
		},
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LoginResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest N502
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest N503
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// </editor-fold> //////////////////////////////////////////////////////////////
